model_type: CRE
use_station_elev: true
z_is_depth_positive: true
cre_reference_margin_m: 0.0
cre_typical_station_elevation_m: null
cre_n_layers: 1
apply_station_elevation_delay: false
lat0: 35.0
lon0: 140.0
origin0: '2026-01-01T00:00:00'
dt_sec: 10.0
max_events: 0
default_depth_km: 0.5
fix_depth: false
arc_use_jma_flag: false
arc_p_centroid_top_n: 1
arc_origin_time_offset_sec: 1.0
das_station_prefix: D
das_phase_weight_code: 3
uncertainty_plot:
  enabled: true
  display_mode: projection
  sigma_scale_sec: 0.05
  poor_thresh_km: 5.0
  clip_km: 10.0
  n_ellipse_points: 100
  ellipse_lw: 0.8
  ellipse_alpha: 0.85
  slice:
    xy:
      enabled: true
      coord_m: 500.0
      half_thickness_m: 10.0
    xz:
      enabled: true
      coord_m: 5000.0
      half_thickness_m: 1.0
    yz:
      enabled: true
      coord_m: 5000.0
      half_thickness_m: 1.0
heatmap:
  enabled: true
  metrics:
  - err3d_m
  - horiz_m
  - dz_m
  - ERH
  - ERZ
  slices:
    xy_all_depths: true
    xz_center_y: true
    yz_center_x: true
  scale:
    percentile: 99
    global_across_slices: true
    dz_symmetric: true
  output:
    save_npy: true
    save_axes_json: true
    out_dirname: heatmaps
event_subsample:
  stride_ijk:
  - 2
  - 2
  - 2
event_filter:
  z_range_m:
  - 500.0
  - null
dataset_dir: /workspace/data/synthe/synth_surface25_das9_2km_uniform_stride101010_noNoise
sim_yaml: case_uniform_grid201x201x61_surface5x5_das3x3_vwell2km_stride101010_noNoise.yaml
outputs_dir: case_das2_0_1000m_dec10
template_cmd: /workspace/external_source/hyp1.40/template/template.cmd
hypoinverse_exe: /workspace/external_source/hyp1.40/hypoinverse.exe
receiver_geometry: recv_surface25_das9_2km.npy
station_subset:
  surface_indices: []
  das_indices:
  - 0
  - 10
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
  - 90
  - 100
